/**
 * Northpower.Planned.Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: edge
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkOrderActivity } from './workOrderActivity';


export interface WorkOrder { 
    id: string;
    clientId: number;
    workTypeId: number;
    clientRequestId?: string;
    requested: Date;
    received: Date;
    status: number;
    statusChanged: Date;
    description?: string;
    scheduledStart: Date;
    scheduledEnd: Date;
    activities?: Array<WorkOrderActivity>;
}
